spring.datasource.url=jdbc:postgresql://localhost:5432/ADS
spring.application.name=ADS
spring.datasource.username=Anton
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.change-log=classpath:liquibase/changelog-master.yml

server.port=8080

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


avatars.dir.path=uploads/avatars/
ads.dir.path=/images/